version: '3.7'

services:
    server:
        container_name: dj
        build:
            context: ./server/khashashin/
        restart: unless-stopped
        expose:
            - 8000
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/media
        command: gunicorn khashashin.wsgi:application --bind 0.0.0.0:8000
        env_file:
            - ./server/khashashin/.env
        depends_on:
            - db
    certbot:
        container_name: cerbot
        image: certbot/certbot
        volumes:
            - www_volume:/usr/share/nginx/html
            - certbot_etc:/etc/letsencrypt
            - certbot_var:/var/lib/letsencrypt
        depends_on:
            - nginx
        command: certonly --webroot --webroot-path=/usr/share/nginx/html --email khashashin@gmail.com --agree-tos --no-eff-email --force-renewal -d khas.dev -d www.khas.dev
    db:
        container_name: postgres
        image: postgres:12.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=khashashin
            - POSTGRES_PASSWORD=khashashin_pw
            - POSTGRES_DB=khashashin_dev_db
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL=khashashin@khas.dev
            - PGADMIN_DEFAULT_PASSWORD=khashashin_pw
            - PGADMIN_LISTEN_PORT=6553
        expose:
            - 6553
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        links:
            - db:pgsql-server
        depends_on:
            - db
    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/media
            - certbot_etc:/etc/letsencrypt
            - certbot_var:/var/lib/letsencrypt
            - www_volume:/usr/share/nginx/html
            - dhparam:/etc/ssl/certs
        ports:
            - 1337:80
            - 80:80
            - 443:443
        depends_on:
            - server

volumes:
    postgres_data:
    static_volume:
    media_volume:
    pgadmin_data:
    www_volume:
    certbot_etc:
    certbot_var:
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: /home/khashashin/khashashin/nginx/dhparam/
            o: bind

