# Generated by Django 2.0.8 on 2018-08-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_section',
            field=models.ForeignKey(blank=True, help_text='Blog section. Will display social links', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Blog Posts'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_section',
            field=models.ForeignKey(blank=True, help_text='Contact links section. Will display social links', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Social Links'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_section',
            field=models.ForeignKey(blank=True, help_text='GitHub Graph section. Will display GraphQL graphic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='GitHub Graphic'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Profile Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_under_image',
            field=models.CharField(blank=True, help_text='Write an introduction for the bakery', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_section',
            field=models.ForeignKey(blank=True, help_text='Twitter section. Will display GraphQL graphic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Recently twitts'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
    ]
